name: main
on:
  push:
    branches:
      - main

jobs:
  build-kevin:
    runs-on: kevin
    steps:
      - uses: actions/checkout@v2

      - name: copy .env file
        run : cp ~/project/send-my-geo/.env .
      - name: create python virtual environment
        run: python3 -m venv venv
      - name: activate python virtual environment
        run: source venv/bin/activate
      - name: check current directory
        run: echo $PWD
      - name: install npm dependencies
        run:  npm install
      - name: install python dependencies
        run:  pip install -r requirements.txt
      - name: restart sniffer
        run: pm2 restart udp2db.py
      - name: restart server
        run: sudo pm2 restart server.js