name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: pm2 stop
        run: pm2 delete all
      - name: install dependencies
        run: |
          pip install pymysql
          pip install cryptography
          pip install python-dotenv
          npm install
      - name: change directory and pull changes
        run: cd ~/project/send-my-geo && git pull
      - name: start services
        run: |
          pm2 start udp2db.py
          pm2 start server.js
      - name: check services running correctly
        run: pm2 list
