name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: kevin
    steps:
      - uses: actions/checkout@v2

      - name: copy .env file
        run : cp ~/project/send-my-geo/.env .
      - name: install dependencies
        run: |
          pip install pymysql
          pip install cryptography
          pip install python-dotenv
          npm install
      - name: restart sniffer
        run: sudo pm2 restart udp2db.py
      - name: restart server
        run: sudo pm2 restart server.js