name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - kevin
      - Jhonatan
      - Eduardo

jobs:
  build-main-kevin: # update server when main branch is updated
    runs-on: kevin
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: copy .env file
        run : cp ~/env-variables/.env .
      - name: Restart sniffer
        run: sudo pm2 restart udp2db.py
      - name: install npm dependencies
        run:  npm install
      - name: restart server
        run: sudo pm2 restart main-server
      - name: verify all services are running
        run: sudo pm2 list

  build-test-kevin: # update server when test branch is updated
    runs-on: kevin-test
    if: github.ref == 'refs/heads/kevin'
    steps:
      - uses: actions/checkout@v2

      - name: copy .env file
        run : cp ~/env-variables/.env .
      - name: change server port
        run: echo "PORT=9000" >> .env
      - name: install npm dependencies
        run:  npm install
      - name: restart server
        run: sudo pm2 restart test-server
      - name: verify verify all services are running
        run: sudo pm2 list

  build-eduardo:
    runs-on: eduardo
    steps:
      - uses: actions/checkout@v2

      - name: copy .env file
        run : cp ~/env-variables/.env .
      - name: Restart sniffer
        run: sudo pm2 restart udp2db.py
      - name: install npm dependencies
        run:  npm install
      - name: restart server
        run: sudo pm2 restart server.js
      - name: verify server and sniffer are running
        run: sudo pm2 list

  build-jhonatan:
    runs-on: jhonatan
    steps:
      - uses: actions/checkout@v2

      - name: copy .env file
        run : cp ~/env-variables/.env .
      - name: Restart sniffer
        run: sudo pm2 restart udp2db.py
      - name: install npm dependencies
        run:  npm install
      - name: restart server
        run: sudo pm2 restart server.js
      - name: verify server and sniffer are running
        run: sudo pm2 list